swift run -c release

#DYLD_PRINT_OPTS=1 \
#DYLD_PRINT_ENV=1 \
#DYLD_PRINT_LIBRARIES=1 \
#DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 \
#DYLD_PRINT_STATISTICS=1 \
#DYLD_PRINT_INITIALIZERS=1 \
#DYLD_PRINT_APIS=1 \
#DYLD_PRINT_BINDINGS=1 \
#DYLD_PRINT_DOFS=1 \
#DYLD_PRINT_RPATHS=1 \

DYLD_PRINT_RPATHS=1 \
.build/arm64-apple-macosx/release/Workspace
